#!/usr/bin/env python3
"""rocket-launcher: Lightweight DBus service for launching apps from KWin scripts."""
import subprocess
import sys
import os

try:
    from gi.repository import Gio, GLib
except ImportError:
    # Fallback: just run the command if no DBus
    if len(sys.argv) > 1:
        subprocess.Popen(sys.argv[1].split(), start_new_session=True)
    sys.exit(0)

BUS_NAME = "org.Rocket.Launcher"
OBJ_PATH = "/org/rocket/launcher"
IFACE = "org.Rocket.Launcher"

INTROSPECTION = f"""<node>
  <interface name="{IFACE}">
    <method name="Exec">
      <arg direction="in" type="s" name="command"/>
    </method>
    <method name="ExecInTerminal">
      <arg direction="in" type="s" name="command"/>
    </method>
  </interface>
</node>"""


class LauncherService:
    def __init__(self):
        self.connection = Gio.bus_get_sync(Gio.BusType.SESSION, None)
        self.connection.register_object(
            OBJ_PATH,
            Gio.DBusNodeInfo.new_for_xml(INTROSPECTION).interfaces[0],
            self.handle_method_call,
            None, None
        )

    def handle_method_call(self, connection, sender, object_path, interface_name, method_name, parameters, invocation):
        if method_name == "Exec":
            cmd = parameters.unpack()[0]
            subprocess.Popen(cmd.split(), start_new_session=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            invocation.return_value(GLib.Variant("(b)", (True,)))
        elif method_name == "ExecInTerminal":
            cmd = parameters.unpack()[0]
            subprocess.Popen(["kitty", cmd], start_new_session=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            invocation.return_value(GLib.Variant("(b)", (True,)))

    def run(self):
        self.owner_id = Gio.bus_own_name(
            Gio.BusType.SESSION, BUS_NAME,
            Gio.BusNameOwnerFlags.NONE, None, None, None
        )
        loop = GLib.MainLoop()
        try:
            loop.run()
        except KeyboardInterrupt:
            Gio.bus_unown_name(self.owner_id)
            loop.quit()


if __name__ == "__main__":
    if "--exec" in sys.argv:
        idx = sys.argv.index("--exec")
        if idx + 1 < len(sys.argv):
            subprocess.Popen(sys.argv[idx + 1].split(), start_new_session=True)
        sys.exit(0)
    else:
        LauncherService().run()
